service: telegram-bot
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  environment:
    TELEGRAM_TOKEN: '1248279229:AAFIcyEfBr5n40l7OXoGD8d4MiAxbHDyfhw'



functions:
  post:
    handler: handler.start
    events:
      - http:
          path: my-custom-url
          method: post
          cors: true